### ISSUE TITLE
Error when running mix phx.server

### ISSUE THREAD

**Issue by jburky** [powelli13/dara-dots#14]
```ERROR in ./js/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
BrowserslistError: [BABEL] c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\js\app.js: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query. (While processing: "c:\\Users\\jburk\\Development\\elixir\\dara-dots\\game_server_umbrella\\apps\\game_server_web\\assets\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at unknownQuery (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\browserslist\index.js:285:10)
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\browserslist\index.js:372:11
    at Array.reduce (<anonymous>)
    at resolve (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\browserslist\index.js:318:18)
    at browserslist (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\browserslist\index.js:443:21)
    at getTargets (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\helper-compilation-targets\lib\index.js:199:48)    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\preset-env\lib\index.js:258:57
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\config\full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\gensync-utils\async.js:26:3)    at Generator.next (<anonymous>)
    at step (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:254:32)
    at evaluateAsync (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:284:5)
    at Function.errback (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:108:7)
    at errback (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\gensync-utils\async.js:70:18)
    at async (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:183:31)
    at onFirstPause (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:209:13)
    at Generator.next (<anonymous>)
    at cachedFunction (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\config\caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPresetDescriptor (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\config\full.js:292:43)
    at loadPresetDescriptor.next (<anonymous>)
    at recurseDescriptors (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\config\full.js:107:30)
    at recurseDescriptors.next (<anonymous>)
    at loadFullConfig (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\config\full.js:142:6)
    at loadFullConfig.next (<anonymous>)
    at Function.transform (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\transform.js:25:45)
    at transform.next (<anonymous>)
    at step (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:262:25)
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:266:13
    at async.call.result.err.err (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:216:11)
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:184:28
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\@babel\core\lib\gensync-utils\async.js:72:7
    at c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:108:33
    at step (c:\Users\jburk\Development\elixir\dara-dots\game_server_umbrella\apps\game_server_web\assets\node_modules\gensync\index.js:280:14)```

**Comment by powelli13** [comment]
Hey Jason unfortunately I'm not able to recreate this issue even with a fresh setup. When searching around I saw this issue: https://github.com/angular/angular-cli/issues/15367 and in the discussion there are some links to other issues and comments that look like promising fixes. Maybe try some of those proposed fixes and post the results here?
